dist: bionic
language: go
go:
- '1.13'
- '1.14'
- '1.15'
- '1.16'
- '1.17'
install:
- go get -u golang.org/x/lint/golint
script:
- if [ -n "$DOCKER_PASSWORD" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
  --password-stdin ; fi
- make docker-test
env:
  global:
  - secure: at3ftkWYwIW5ZHqwfm7LEQxlLyCZvFSpzKKnUbirYnVFn/puAQELp7Zuu6/KhlpW+naO9a//ZBTgZxslVHoyE08ZFiGEA5xtmbDGKLGkvTJE26L8WIYwAd1goy3ahfpH8fXfqQmBGEhIo86f6vY2LMvFOIMTk4eWj21wuje+HTQjVR6A1NrFdpMhubM6CZae6wdGxywjeskAQWbBAzoF1WQWwqhQobhunPDHoXAidB2bxD37zt301s8U+VVcCOPazLx4UOP/339ZRe3+egVng1WJdkEKL8HqPCl23LOFW3sCaeC+Kj/56gezS9DyCq3LJC93Rmj+E8bQF3Dngelv7W3++UvHR7RnCafMc8L4ZFNb5it7lA6ewEe6neaotBFiWjRDfeFlNfRNuBryVvw7GhlMGe7jSP9CC+5W3U9EHkbypQ3sVumq5LQsuzlN6AsN73NnS/t2djjsWW/b3CMF1tE5J7ghEAFXXZPepem9FrYnSyrCtlm6N3hJZDOs0FkHpCfPZCztiy6EQnEgnJI79kEQBcRz8InCSVOYAqPg/TOscK1fkUVSfkfTezWVK3wSL9zmKUZfHv16VJwaFfNn3YNIryIN4sB0MxkagLLV1TSooHoakL9u4MRW8kKQFl4N+hZ3pFSJanmq5kXvGbwpY9tvado6fcNfkPCYTgT3AO8=
  - secure: GtJBNolBV4yroCM9Y4vjpLG3QuL4WmgrXdoShG06xTHz0ZUAiQyK52iXHWl/XnyvfZYP95x3vBKStcxCzUE8YYp7IthBZg9U8GAobtTGutGZk6CMd/KIbeZELao4BNkg251x0huETQ8q/Pb4RyBVCaIZJoJbT+cYgr6oSy8pdYlfeqV04b7Cjv8xHAh47Ii0ACEVAYWYsc/eroIWt2YO4IM7x3iQZ2oXbzD3+BksgS7O5imJODRtzq2UPiDm4zc+avx8WZVVaxt67CSeAD6cjyuTjP5mLXcJjphU4ZGWeyqMnAHi8fQ+6bmvkZYrVECYZqpgUAbpuONUpHy05uxg/oRCdkR+02nZp3uTIvWqTgtpB0ZQkL2ejZnlxFAJA34fAukECaJ9F2SAeVkp05uTz/p7LvnjW0x47igflTU6X464jklJoqKuXX+mdSN6hWJ7r17NV7QzkCozSgMdNpKIEMm2SDgfQNG1axckFg2Iu2TSAo7J5tzIbrXj1ZRiMEfk75eVqqi5ggFkaYx/90oSetaat/JGQBofvnWTEDJxguREjQSpmzEWPqehpv2wObSbfyo+CmbwnklQyDfhzREsnIJscOcX9PNCPip7pKvLnFgd1WRemJ6r+0dfpdnsll8E4+7WwPyh1nvVaxXH0I8JUqXPfggNoeMMUjTLwoqupoM=