dist: bionic
language: go
go:
- '1.13'
- '1.14'
- '1.15'
- '1.16'
- '1.17'
install:
- go get -u golang.org/x/lint/golint
script:
- if [ -n "$DOCKER_PASSWORD" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
  --password-stdin ; fi
- make docker-test